### ISSUE TITLE
Curveball and Vercel

### ISSUE THREAD

**Issue by ghost** [curveball/aws-lambda#24]
I'm confused. Can you please tell me if Curveball supports Vercel somehow?
https://vercel.com/docs/runtimes#advanced-usage/advanced-node-js-usage/aws-lambda-api

**Comment by evert** [comment]
I don't really know what Vercel is, but this link suggests that it supports 'regular' AWS Lambda functions, so that would mean that curveball also works with it.

The examples in this package also use `handler` as the default export, so that also suggests that the configuration you linked also works with curveball.

**Comment by ghost** [comment]
Nevermind. I have come to the conclussion that AWS Lambda is better than the aforementioned company in every aspect I can think of. I will close this issue now. Thanks.
